ROBORIO_PWM_0 = 0
ROBORIO_PWM_1 = 1

LEFT_FRONT_MOTOR_CAN_ID = 56
LEFT_MIDDLE_MOTOR_CAN_ID = 55
LEFT_BACK_MOTOR_CAN_ID = 54

RIGHT_FRONT_MOTOR_CAN_ID = 53
RIGHT_MIDDLE_MOTOR_CAN_ID = 52
RIGHT_BACK_MOTOR_CAN_ID = 51

ELEVATOR_MOTOR_CAN_ID = 57
SHOOTER_MOTOR_CAN_ID = 58
LIFT_MOTOR_CAN_ID = 59
INTAKE_MOTOR_CAN_ID = 60

PDP_CAN_ID = 62

PCM_PORT_0 = 0
PCM_PORT_1 = 1
PCM_PORT_2 = 2
PCM_PORT_3 = 3

JOYSTICK_0 = 0
JOYSTICK_1 = 1

JOYSTICK_0_THROTTLE_CHANNEL = 1
JOYSTICK_0_Z_CHANNEL = 4

JOYSTICK_1_THROTTLE_CHANNEL = 2
JOYSTICK_1_Z_CHANNEL = 3

BUTTON_1 = 1
BUTTON_2 = 2
BUTTON_3 = 3
BUTTON_4 = 4

DRIVER_JOYSTICK_BUTTON_A = BUTTON_1
DRIVER_JOYSTICK_BUTTON_B = BUTTON_2

CODRIVER_JOYSTICK_BUTTON_A = BUTTON_1
CODRIVER_JOYSTICK_BUTTON_B = BUTTON_2
CODRIVER_JOYSTICK_BUTTON_X = BUTTON_3
CODRIVER_JOYSTICK_BUTTON_Y = BUTTON_4

DRIVETRAIN_SQUARED_INPUTS = True

ELEVATOR_SPEED_UP = 0.3
ELEVATOR_SPEED_DOWN = -0.3

LIFTER_SPEED_UP = 0.3
LIFTER_SPEED_DOWN = -0.3

TRIGGER_ACTIVATION_THRESHOLD = 0.1

INTAKE_SPEED_IN = 0.3

SHOOTER_SPEED_SHOOT = 1

MOTOR_NEUTRAL = 0
